#ifndef RENDER_OPTIONS_H
#define RENDER_OPTIONS_H

#ifndef RENDERER_MAX_BIND_GROUP
#define RENDERER_MAX_BIND_GROUP 3
#endif

#ifndef RENDERER_MAX_DYN_BIND_GROUP
#define RENDERER_MAX_DYN_BIND_GROUP 1
#endif

#ifndef RENDERER_MAX_VTX_BUFFERS
#define RENDERER_MAX_VTX_BUFFERS 3
#endif

#define RENDERER_DYN_OFFSET RENDERER_MAX_BIND_GROUP

#endif